server:
  port: 8210
spring:
  application:
    name: zuul
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
zuul:
  routes:
    provider: /p/**

##zuul.routes.provider 给服务提供者设置映射